close all
clear all
hold on

%---
% plot streamlines generated by flow_2d
%---

file1 = fopen('body_ax.str');

Ido=1;

%---
while(Ido==1)

 N=fscanf(file1,'%d',[1,1]);
 if(N==0) break; end

 clear x
 clear y

 for i=1:N
  idle=fscanf(file1,'%d',[1,1]);
  x(i)=fscanf(file1,'%f',[1,1]);
  y(i)=fscanf(file1,'%f',[1,1]);
 end
 plot( x,y,'k')
 plot( x,-y,'k')

end
%---

%plot([-2 2],[0 0],'k')
axis equal
%axis square
set(gca,'fontsize',15)
xlabel('x','fontsize',15)
ylabel('y','fontsize',15)
axis([-2.0 2.0 -2.0 2.0])
box on
