close all
clear all
hold on

%---
% plot streamlines generated by flow_2d
%---

file1 = fopen('flow_2d.str');

Ido=1;

%---
while(Ido==1)

 N=fscanf(file1,'%d',[1,1]);
 if(N==0) break; end

 clear x
 clear y

 for i=1:N
  idle=fscanf(file1,'%d',[1,1]);
  x(i)=fscanf(file1,'%f',[1,1]);
  y(i)=fscanf(file1,'%f',[1,1]);
 end
 plot( x,y,'k')
 plot( x+1,y,'k')
 plot( x-1,y,'k')

end
%---

axis equal
%axis square
set(gca,'fontsize',15)
xlabel('x','fontsize',15)
ylabel('y','fontsize',15)
axis([-1.0 1.0 -1.0 1.0])
box


