all:
	cd 01_num_meth; make all
	cd 02_grids; make all
	cd 03_laplace; make all
	cd 04_helmholtz; make all
	cd 05_stokes; make all
clean:
	cd 01_num_meth; make clean
	cd 02_grids; make clean
	cd 03_laplace; make clean
	cd 04_helmholtz; make clean
	cd 05_stokes; make clean
purge:
	cd 01_num_meth; make purge
	cd 02_grids; make purge
	cd 03_laplace; make purge
	cd 04_helmholtz; make purge
	cd 05_stokes; make purge
