all:
	cd grid_2d; make all
	cd prd_2d; make all
	cd prd_2d_open; make all
	cd prd_2d_pr; make all
	cd prd_ax; make all
	cd prd_3d; make all
	cd trgl; make all
	cd trgl_flat; make all
clean:
	cd grid_2d; make clean
	cd prd_2d; make clean
	cd prd_2d_open; make clean
	cd prd_2d_pr; make clean
	cd prd_ax; make clean
	cd prd_3d; make clean
	cd trgl; make clean
	cd trgl_flat; make clean
purge:
	cd grid_2d; make purge
	cd prd_2d; make purge
	cd prd_2d_open; make purge
	cd prd_2d_pr; make purge
	cd prd_ax; make purge
	cd prd_3d; make purge
	cd trgl; make purge
	cd trgl_flat; make purge
